=== Deltares-research/KnowledgeRules/XMLSchema/AutecologyXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Knowledge Rules project ( Copyright under GPLv3 by Stichting Deltares ) -->
<schema xmlns:AutXML="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<element name="AutecologyXML" type="AutXML:AutecologyXMLConfigComplexType"/>
	<complexType name="AutecologyXMLConfigComplexType">
		<sequence>
			<element name="Topic" type="AutXML:TopicComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Autecology" type="AutXML:AutecologyComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="ContentDescription" type="AutXML:CDComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Documentation" type="AutXML:DocumentationComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="DataSources" type="AutXML:DataSourcesComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TopicComplexType">
		<choice>
			<element name="Species" type="AutXML:SpeciesComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="WFDindicator" type="AutXML:WFDIComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="SpeciesComplexType">
		<sequence>
			<element name="EoLpagenr" type="AutXML:ExternalIntegerSimpleType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="LatName" type="string" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<choice>
				<element name="SpecCode" type="string" minOccurs="0" maxOccurs="1">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="WFDIComplexType">
		<sequence>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="AutecologyComplexType">
		<sequence>
			<element name="ModelType" type="AutXML:ModelTypeComplexType" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ModelTypeComplexType">
		<sequence>
			<element name="System" type="AutXML:SystemComplexType" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="SystemComplexType">
		<sequence>
			<element name="Scope" type="AutXML:ScopeComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemDescription" type="AutXML:CDComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemFlowDiagrams" type="AutXML:SystemFlowDiagramsComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="KnowledgeRules" type="AutXML:KnowledgeRulesComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ScopeComplexType">
		<sequence>
			<element name="SpatialScope" type="AutXML:SpatialScopeComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="TemporalScope" type="AutXML:TemporalScopeComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SpatialScopeComplexType">
		<sequence>
			<element name="GeoNames" type="AutXML:GeoNamesComplexType" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="GeoNamesComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="id" type="integer" use="required"/>
	</complexType>
	<complexType name="TemporalScopeComplexType">
		<sequence>
			<element name="StartDate" type="AutXML:dateType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="EndDate" type="AutXML:dateType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SystemFlowDiagramsComplexType">
		<sequence>
			<element name="FlowDiagram" type="AutXML:FlowDiagramComplexType" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FlowDiagramComplexType">
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="KnowledgeRulesComplexType">
		<choice>
			<element name="ResponseCurve" type="AutXML:ResponseCurveComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="FormulaBased" type="AutXML:FormulaBasedComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="ResponseCurveComplexType">
		<sequence>
			<element name="type" type="AutXML:TypeSingleType" minOccurs="0"/>
			<element name="layername" type="string" minOccurs="0"/>
			<element name="unit" type="string" minOccurs="0"/>
			<element name="statistic" type="string" minOccurs="0"/>
			<element name="description" type="string" minOccurs="0"/>
			<element name="author" type="string" minOccurs="0"/>
			<element name="date" type="AutXML:dateType" minOccurs="0"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="0"/>
			<choice>
				<element name="valuesScalar" type="AutXML:RCValuesScalarComplexType" minOccurs="0"/>
				<element name="valuesCategorical" type="AutXML:RCValuesCategoricalComplexType" minOccurs="0"/>
				<element name="valuesRangeCategorical" type="AutXML:RCValuesRangeCategoricalComplexType" minOccurs="0"/>
				<element name="valuesRanges" type="AutXML:RCValuesRangesComplexType" minOccurs="0"/>
			</choice>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="FormulaBasedComplexType">
		<sequence>
			<element name="layername" type="string" minOccurs="0"/>
			<element name="unit" type="string" minOccurs="0"/>
			<element name="statistic" type="string" minOccurs="0"/>
			<element name="description" type="string" minOccurs="0"/>
			<element name="author" type="string" minOccurs="0"/>
			<element name="date" type="AutXML:dateType" minOccurs="0"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="0"/>
			<element name="output" type="string" minOccurs="0"/>
			<element name="equation" type="string" minOccurs="0"/>
			<element name="Parameters" type="AutXML:FBParametersComplexType" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ReferencesComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBParametersComplexType">
		<sequence>
			<element name="valuesConstant" type="AutXML:FBConstantValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="valuesScalar" type="AutXML:FBScalarValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesScalarComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarRCComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterCategoricalRCComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangeCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangeCategoricalRCComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangesRCComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBConstantValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterConstantFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="constant"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="FBScalarValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="scalar"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterConstantFBComplexType">
		<attribute name="constantset" type="string" use="required"/>
		<attribute name="value" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarFBComplexType">
		<attribute name="min" type="string" use="required"/>
		<attribute name="max" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarRCComplexType">
		<attribute name="value" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterCategoricalRCComplexType">
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangeCategoricalRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangesRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="CDComplexType">
		<sequence>
			<element name="Description" type="AutXML:DescriptionComplexType"/>
		</sequence>
	</complexType>
	<complexType name="DocumentationComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DataSourcesComplexType"/>
	<complexType name="CommonNamesComplexType">
		<sequence>
			<element name="Name" type="AutXML:NameComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="NameComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="DescriptionComplexType">
		<sequence>
			<element name="text" type="string"/>
		</sequence>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="ReferenceComplexType">
		<choice>
			<element name="html" type="string" minOccurs="0" maxOccurs="1"/>
		</choice>
		<attribute name="author" type="string" use="required"/>
		<attribute name="year" type="string" use="required"/>
		<attribute name="title" type="string" use="required"/>
		<attribute name="journal" type="string" use="required"/>
		<attribute name="identification" type="string" use="required"/>
	</complexType>
	<complexType name="DateTimeComplexType">
		<attribute name="date" type="AutXML:dateType" use="required"/>
	</complexType>
	<simpleType name="dateType">
		<restriction base="date">
			<pattern value="\d\d\d\d-\d\d-\d\d"/>
		</restriction>
	</simpleType>
	<simpleType name="TypeSingleType">
		<restriction base="string">
			<enumeration value="scalar"/>
			<enumeration value="categorical"/>
			<enumeration value="range / categorical"/>
			<enumeration value="ranges"/>
		</restriction>
	</simpleType>
	<simpleType name="ExternalIntegerSimpleType">
		<union memberTypes="integer">
			<simpleType>
				<restriction base="string">
					<pattern value="[$][a-zA-Z0-9.()*/+-_]+[$]"/>
				</restriction>
			</simpleType>
		</union>
	</simpleType>
</schema>

=== Deltares-research/KnowledgeRules/_knowledgerules/species/Molluscs/Mytilus edulis.xml
<?xml version="1.0" encoding="UTF-8"?>
<AutecologyXML xmlns="http://www.wldelft.nl/fews" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wldelft.nl/fews ../../../XMLSchema/AutecologyXML.xsd">
	<Topic>
		<Species>
			<EoLpagenr>46466840</EoLpagenr>
			<LatName>Mytilus edulis</LatName>
			<CommonNames>
				<Name name = "Mossel" language = "NL"/>
			</CommonNames>
			<SpecCode/>
		</Species>
		</Topic>
	<Autecology>
		<ModelType name="HSI">
			<System name="adult">
				<Scope>
					<SpatialScope>
						<GeoNames name="Netherlands" id="2750405"/>
					</SpatialScope>
					<TemporalScope>
						<StartDate>2002-01-01</StartDate>
						<EndDate>2002-01-01</EndDate>
					</TemporalScope>
				</Scope>
				<SystemDescription>
					<Description language="NL">
					<text><![CDATA[<h1 id="Mossel-Mytilusedulis-Onzekerheidenvalidatie">Onzekerheid en validatie</h1>

<p>Deze dosis-effect relaties zijn gevalideerd voor de Waddenzee.</p>

<h1 id="Mossel-Mytilusedulis-Toepasbaarheid">Toepasbaarheid</h1>

<p>Deze dosis-effect relaties zijn toepasbaar op zoute wateren in Nederland.</p>

<h1 id="Mossel-Mytilusedulis-Voorbeeldproject">Voorbeeld project</h1>

<p>Er is geen voorbeeld projekt voor de mossel.</p>]]></text>
					</Description>
				</SystemDescription>
				<SystemFlowDiagrams>
					<FlowDiagram name="HGI">
						<From name="Habitat_quality">
							<label>"Habitat_quality"</label>
							<equation>min</equation>
							<To>Maximum_flow_velocity</To>
							<To>Maximum_orbital_velocity</To>
							<To>Flooding</To>
							<To>Salinity</To>
							<To>Oxygen_concentration</To>
							<To>Waterdepth</To>
						</From>
					</FlowDiagram>
				</SystemFlowDiagrams>
				<KnowledgeRules>		
					<ResponseCurve name="Maximum_flow_velocity">
						<type>scalar</type>
						<layername>"Maximum_flow_velocity"</layername>
						<unit>"m/s"</unit>
						<statistic>maximum</statistic>
						<description>"Maximum flow velocity of the water in meters per second"</description>
						<author>"Valesca Harezlak"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="Brinkman, A.G., Dankers, N.M.J.A., van Stralen, M.R." year="2002" title="" journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0.0" HSI="0.0"/>
							<parameter value="0.2" HSI="0.0"/>
							<parameter value="0.5" HSI="0.5"/>
							<parameter value="0.8" HSI="1.0"/>
							<parameter value="1.0" HSI="0.75"/>
							<parameter value="1.2" HSI="0.4"/>
							<parameter value="1.5" HSI="0.2"/>
							<parameter value="1.8" HSI="0.0"/>
						</valuesScalar>
					</ResponseCurve>
					<ResponseCurve name="Maximum_orbital_velocity">
						<type>scalar</type>
						<layername>"Maximum_orbital_velocity"</layername>
						<unit>"m/s"</unit>
						<statistic>maximum</statistic>
						<description>"Maximum orbital velocity of the water in meters per second"</description>
						<author>"Valesca Harezlak"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="Brinkman, A.G., Dankers, N.M.J.A., van Stralen, M.R." year="2002" title="" journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0.0" HSI="0.4"/>
							<parameter value="0.2" HSI="1.0"/>
							<parameter value="0.3" HSI="0.5"/>
							<parameter value="0.5" HSI="0.2"/>
							<parameter value="0.6" HSI="0.0"/>
						</valuesScalar>
					</ResponseCurve>
					<ResponseCurve name="Flooding">
						<type>scalar</type>
						<layername>"Flooding"</layername>
						<unit>"%"</unit>
						<statistic>maximum</statistic>
						<description>"Flooding duration in percent"</description>
						<author>"Valesca Harezlak"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="Brinkman, A.G., Dankers, N.M.J.A., van Stralen, M.R." year="2002" title="" journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0" HSI="0.0"/>
							<parameter value="55" HSI="0.0"/>
							<parameter value="70" HSI="0.5"/>
							<parameter value="100" HSI="1.0"/>
						</valuesScalar>
					</ResponseCurve>
					<ResponseCurve name="Salinity">
						<type>scalar</type>
						<layername>"Salinity"</layername>
						<unit>"gCl/l"</unit>
						<statistic>maximum</statistic>
						<description>"Flooding duration in percent"</description>
						<author>"Valesca Harezlak"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="http://www.vliz.be/docs/groterede/GR13_blauwe_mossel.pdf" year="" title="" journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0" HSI="0.0"/>
							<parameter value="4" HSI="0.0"/>
							<parameter value="10" HSI="1.0"/>
							<parameter value="15" HSI="1.0"/>
						</valuesScalar>
					</ResponseCurve>
					<ResponseCurve name="Oxygen_concentration">
						<type>scalar</type>
						<layername>"Oxygen_concentration"</layername>
						<unit>"mg/l"</unit>
						<statistic>average</statistic>
						<description>"Average oxygen concentration in milligrams per liter"</description>
						<author>"Valesca Harezlak"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="" year="" title="This relationship is based on information from the Zebra mussel and the Japanese oyster and needs to be improved if more information is available." journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0" HSI="0.0"/>
							<parameter value="5" HSI="0.0"/>
							<parameter value="7" HSI="1.0"/>
							<parameter value="15" HSI="1.0"/>
						</valuesScalar>
					</ResponseCurve>
					<ResponseCurve name="Waterdepth">
						<type>range / categorical</type>
						<layername>"Waterdepth"</layername>
						<unit>"m"</unit>
						<statistic>average</statistic>
						<description>"Waterdepth in meters"</description>
						<author>"Valesca Harezlak"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="" year="" title="" journal="" identification=""/>
						</references>
						<valuesRangeCategorical>
							<parameter rangemin="0" rangemax="2" cat="0 - 2" HSI="0.8"/>
							<parameter rangemin="2" rangemax="5" cat="2 - 5" HSI="1.0"/>
							<parameter rangemin="5" rangemax="10" cat="5 - 10" HSI="0.6"/>
							<parameter rangemin="10" rangemax="20" cat="10 - 20" HSI="0.3"/>
							<parameter rangemin="20" rangemax="999999" cat="> 20" HSI="0.0"/>
						</valuesRangeCategorical>
					</ResponseCurve>
				</KnowledgeRules>
			</System>
		</ModelType>
	</Autecology>
	<ContentDescription>
		<Description language="NL"><text><![CDATA[<h2 id="Mossel-Mytilusedulis-Algemeenvoorkomen">Algemeen voorkomen</h2>

<p>De mossel (<em>mytilus edulis</em>) kent een groot verspreidingsgebied en wordt gevonden van Noord-Noorwegen tot Noordwest-Afrika. De mossel komt ook voor langs vrijwel de gehele oostkust van Noord-Amerika van de poolzee tot South Carolina, en langs de westkust van Alaska tot Baja California (Mexico).</p>

<h3 id="Mossel-Mytilusedulis-Milieurandvoorwaarden">Milieurandvoorwaarden</h3>

<p>De mossel wordt vooral in het intergetijde gebied en dieper aangetroffen. Mosselen hechten vaak op harde ondergrond, zoals steigers of dijkvoeten, of op elkaar. Ze worden vaak aangetroffen in dichte bedden of banken die meerdere jaarklassen bevatten. Deze bedden verheffen zich, door invanging van sediment, boven het omliggende gebied. Als de bedden te hoog worden, worden ze instabiel. Tijdens de winterstormen verdwijnen grote delen van zowel de jonge als de oude mosselbedden.</p>

<h3 id="Mossel-Mytilusedulis-Beheerenontwikkelingskansen">Beheer en ontwikkelingskansen</h3>

<p>De mossel is een geliefd consumptieproduct en wordt daardoor op grote schaal gekweekt. De kweek binnen Nederland vindt voornamelijk plaats in de Oosterschelde.</p>]]></text>
		</Description>
	</ContentDescription>
	<Documentation>
		<reference author="Brinkman, A.G., Dankers, N.M.J.A., van Stralen, M.R." year="2002" title="An analysis of mussel bed habitats in the Dutch Wadden Sea." journal="" identification="Helgoland Marine Research 56: 59-75"/>
		<reference author="" year="" title= "http://www.vliz.be/docs/groterede/GR13_blauwe_mossel.pdf" journal="" identification=""/>
	</Documentation>
	<DataSources/>
</AutecologyXML>
