=== Deltares-research/KnowledgeRules/XMLSchema/AutecologyXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Knowledge Rules project ( Copyright under GPLv3 by Stichting Deltares ) -->
<schema xmlns:AutXML="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<element name="AutecologyXML" type="AutXML:AutecologyXMLConfigComplexType"/>
	<complexType name="AutecologyXMLConfigComplexType">
		<sequence>
			<element name="Topic" type="AutXML:TopicComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Autecology" type="AutXML:AutecologyComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="ContentDescription" type="AutXML:CDComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Documentation" type="AutXML:DocumentationComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="DataSources" type="AutXML:DataSourcesComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TopicComplexType">
		<choice>
			<element name="Species" type="AutXML:SpeciesComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="WFDindicator" type="AutXML:WFDIComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="SpeciesComplexType">
		<sequence>
			<element name="EoLpagenr" type="AutXML:ExternalIntegerSimpleType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="LatName" type="string" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<choice>
				<element name="SpecCode" type="string" minOccurs="0" maxOccurs="1">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="WFDIComplexType">
		<sequence>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="AutecologyComplexType">
		<sequence>
			<element name="ModelType" type="AutXML:ModelTypeComplexType" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ModelTypeComplexType">
		<sequence>
			<element name="System" type="AutXML:SystemComplexType" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="SystemComplexType">
		<sequence>
			<element name="Scope" type="AutXML:ScopeComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemDescription" type="AutXML:CDComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemFlowDiagrams" type="AutXML:SystemFlowDiagramsComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="KnowledgeRules" type="AutXML:KnowledgeRulesComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ScopeComplexType">
		<sequence>
			<element name="SpatialScope" type="AutXML:SpatialScopeComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="TemporalScope" type="AutXML:TemporalScopeComplexType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SpatialScopeComplexType">
		<sequence>
			<element name="GeoNames" type="AutXML:GeoNamesComplexType" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="GeoNamesComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="id" type="integer" use="required"/>
	</complexType>
	<complexType name="TemporalScopeComplexType">
		<sequence>
			<element name="StartDate" type="AutXML:dateType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="EndDate" type="AutXML:dateType" minOccurs="1" maxOccurs="1">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SystemFlowDiagramsComplexType">
		<sequence>
			<element name="FlowDiagram" type="AutXML:FlowDiagramComplexType" minOccurs="1" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FlowDiagramComplexType">
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="KnowledgeRulesComplexType">
		<choice>
			<element name="ResponseCurve" type="AutXML:ResponseCurveComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="FormulaBased" type="AutXML:FormulaBasedComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="ResponseCurveComplexType">
		<sequence>
			<element name="type" type="AutXML:TypeSingleType" minOccurs="0"/>
			<element name="layername" type="string" minOccurs="0"/>
			<element name="unit" type="string" minOccurs="0"/>
			<element name="statistic" type="string" minOccurs="0"/>
			<element name="description" type="string" minOccurs="0"/>
			<element name="author" type="string" minOccurs="0"/>
			<element name="date" type="AutXML:dateType" minOccurs="0"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="0"/>
			<choice>
				<element name="valuesScalar" type="AutXML:RCValuesScalarComplexType" minOccurs="0"/>
				<element name="valuesCategorical" type="AutXML:RCValuesCategoricalComplexType" minOccurs="0"/>
				<element name="valuesRangeCategorical" type="AutXML:RCValuesRangeCategoricalComplexType" minOccurs="0"/>
				<element name="valuesRanges" type="AutXML:RCValuesRangesComplexType" minOccurs="0"/>
			</choice>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="FormulaBasedComplexType">
		<sequence>
			<element name="layername" type="string" minOccurs="0"/>
			<element name="unit" type="string" minOccurs="0"/>
			<element name="statistic" type="string" minOccurs="0"/>
			<element name="description" type="string" minOccurs="0"/>
			<element name="author" type="string" minOccurs="0"/>
			<element name="date" type="AutXML:dateType" minOccurs="0"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="0"/>
			<element name="output" type="string" minOccurs="0"/>
			<element name="equation" type="string" minOccurs="0"/>
			<element name="Parameters" type="AutXML:FBParametersComplexType" minOccurs="0"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ReferencesComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBParametersComplexType">
		<sequence>
			<element name="valuesConstant" type="AutXML:FBConstantValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="valuesScalar" type="AutXML:FBScalarValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesScalarComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarRCComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterCategoricalRCComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangeCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangeCategoricalRCComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangesRCComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBConstantValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterConstantFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="constant"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="FBScalarValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="scalar"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterConstantFBComplexType">
		<attribute name="constantset" type="string" use="required"/>
		<attribute name="value" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarFBComplexType">
		<attribute name="min" type="string" use="required"/>
		<attribute name="max" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarRCComplexType">
		<attribute name="value" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterCategoricalRCComplexType">
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangeCategoricalRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangesRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="CDComplexType">
		<sequence>
			<element name="Description" type="AutXML:DescriptionComplexType"/>
		</sequence>
	</complexType>
	<complexType name="DocumentationComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DataSourcesComplexType"/>
	<complexType name="CommonNamesComplexType">
		<sequence>
			<element name="Name" type="AutXML:NameComplexType" minOccurs="1" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="NameComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="DescriptionComplexType">
		<sequence>
			<element name="text" type="string"/>
		</sequence>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="ReferenceComplexType">
		<choice>
			<element name="html" type="string" minOccurs="0" maxOccurs="1"/>
		</choice>
		<attribute name="author" type="string" use="required"/>
		<attribute name="year" type="string" use="required"/>
		<attribute name="title" type="string" use="required"/>
		<attribute name="journal" type="string" use="required"/>
		<attribute name="identification" type="string" use="required"/>
	</complexType>
	<complexType name="DateTimeComplexType">
		<attribute name="date" type="AutXML:dateType" use="required"/>
	</complexType>
	<simpleType name="dateType">
		<restriction base="date">
			<pattern value="\d\d\d\d-\d\d-\d\d"/>
		</restriction>
	</simpleType>
	<simpleType name="TypeSingleType">
		<restriction base="string">
			<enumeration value="scalar"/>
			<enumeration value="categorical"/>
			<enumeration value="range / categorical"/>
			<enumeration value="ranges"/>
		</restriction>
	</simpleType>
	<simpleType name="ExternalIntegerSimpleType">
		<union memberTypes="integer">
			<simpleType>
				<restriction base="string">
					<pattern value="[$][a-zA-Z0-9.()*/+-_]+[$]"/>
				</restriction>
			</simpleType>
		</union>
	</simpleType>
</schema>

=== Deltares-research/KnowledgeRules/scripting/view_xmls_tool/AutecologyXMLtest.xml
<?xml version="1.0" encoding="UTF-8"?>
<AutecologyXML xmlns="http://www.wldelft.nl/fews" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wldelft.nl/fews ../../XMLSchema/AutecologyXML.xsd">
	<Topic>
		<Species>
		<EoLpagenr>000000</EoLpagenr>
		<LatName>Testus testus</LatName>
		<CommonNames>
			<Name name="Test name" language = "ENG"/>
		</CommonNames>
		<SpecCode/>
		</Species>
	</Topic>
	<Autecology>
		<ModelType name="HSI">
			<System name="testsystem">
				<Scope>
					<SpatialScope>
						<GeoNames name="Earth" id="6295630"/>
					</SpatialScope>
					<TemporalScope>
						<StartDate>2019-01-01</StartDate>
						<EndDate>2019-12-04</EndDate>
					</TemporalScope>
				</Scope>
				<SystemDescription>
					<Description language="ENG">
						<text><![CDATA[Test
TEST]]></text>
					</Description>
				</SystemDescription>
				<SystemFlowDiagrams>
					<FlowDiagram name="TOBEFILLED"/>
				</SystemFlowDiagrams>
				<KnowledgeRules>
					<ResponseCurve name="Chloride">
						<type>scalar</type>
						<layername>"CL"</layername>
						<unit>"g/l"</unit>
						<statistic>minimum</statistic>
						<description>"Tolerable chlorine content for the Zebra mussel species"</description>
						<author>"K.E. van de Wolfshaar, M. Haasnoot"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="K.E. van de Wolfshaar, M. Haasnoot" year="2014" title="" journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0" HSI="1"/>
							<parameter value="1" HSI="1"/>
							<parameter value="1.1" HSI="0"/>
							<parameter value="5" HSI="0"/>
						</valuesScalar>
					</ResponseCurve>
					<ResponseCurve name="Soil">
						<type>categorical</type>
						<layername>"SoilType"</layername>
						<unit>"soil"</unit>
						<statistic>average</statistic>
						<description>"Average soil type tolerable for the Zebra mossel species"</description>
						<author>"Mijke van Oorschot"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="K.E. van de Wolfshaar, M. Haasnoot" year="2014" title="" journal="" identification=""/>
						</references>
						<valuesCategorical>
							<parameter cat="klei" HSI="0.466"/>
							<parameter cat="leem" HSI="0.688"/>
							<parameter cat="zand" HSI="0.743"/>
							<parameter cat="veen" HSI="0.074"/>
							<parameter cat="stortsteen" HSI="0.879"/>
						</valuesCategorical>
					</ResponseCurve>
					<ResponseCurve name="SiltFraction">
						<type>range / categorical</type>
						<layername>"SiltFraction"</layername>
						<unit>"silt fraction / description"</unit>
						<statistic>average</statistic>
						<description>"Average silt content tolerable for the Zebra mossel species"</description>
						<author>"Mijke van Oorschot"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="K.E. van de Wolfshaar, M. Haasnoot" year="2014" title="" journal="" identification=""/>
						</references>
						<valuesRangeCategorical>
							<parameter rangemin="0" rangemax="10" cat="slibarm" HSI="0.753"/>
							<parameter rangemin="10" rangemax="25" cat="matig slibrijk" HSI="0.45"/>
							<parameter rangemin="25" rangemax="100" cat="slibrijk" HSI="0.103"/>
						</valuesRangeCategorical>
					</ResponseCurve>
					<ResponseCurve name="WaterdepthLakes">
						<type>ranges</type>
						<layername>"WaterdepthLakes"</layername>
						<unit>"m"</unit>
						<statistic>average</statistic>
						<description>"Waterdepth tolerable for the Zebra mossel species in Lakes"</description>
						<author>"Mijke van Oorschot"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="K.E. van de Wolfshaar, M. Haasnoot" year="2014" title="" journal="" identification=""/>
						</references>
						<valuesRanges>
							<parameter rangemin="0" rangemax="2" HSI="0.287"/>
							<parameter rangemin="2" rangemax="5" HSI="0.76"/>
							<parameter rangemin="5" rangemax="10" HSI="0.634"/>
							<parameter rangemin="10" rangemax="25" HSI="0.205"/>
							<parameter rangemin="25" rangemax="50" HSI="0.033"/>
							<parameter rangemin="50" rangemax="999999" HSI="0"/>
						</valuesRanges>
					</ResponseCurve>
					<FormulaBased name="P_chara_extinction">
						<layername>"P_chara_extinction"</layername>
						<unit>"-"</unit>
						<statistic>none</statistic>
						<description>"Likeliness of presence for the Chara species"</description>
						<author>"Marjolein Haasnoot"</author>
						<date>2014-07-29</date>
						<references>
							<reference author="M. Haasnoot" year="2014" title="" identification="" journal="">
								<html></html>
							</reference>
						</references>
						<output>"Probability"</output>
						<equation>"1/(1+exp(-(0.247702657+deelgebied-1.280411065*diepte_zom+0.06854636*(diepte_zom^2)-0.278693414*diepte_zom*extinctie-0.163078252*extinctie-0.000435184*strijklengte)))"</equation>
						<Parameters>
							<valuesConstant dataname = "deelgebied" type = "constant" unit = "-">
								<parameter constantset ="MBIJ" value="-0.81302272"/>
								<parameter constantset ="MGZ" value="1.998701637"/>
								<parameter constantset ="MHE" value="0.724567841"/>
								<parameter constantset ="MHH" value="1.733868205"/>
								<parameter constantset ="MHRDz" value="2.214793065"/>
								<parameter constantset ="MIJ" value="1.45711916"/>
							</valuesConstant>
							<valuesScalar dataname = "diepte_zom" type = "scalar" unit = "m" >
								<parameter min="0" max="3.5"/>
							</valuesScalar>
							<valuesScalar dataname = "extinctie" type = "scalar" unit = "m-1" >
								<parameter min="0" max="10"/>
							</valuesScalar>
							<valuesScalar dataname = "strijklengte" type = "scalar" unit = "m" >
								<parameter min="0" max="50000"/>
							</valuesScalar>
						</Parameters>
					</FormulaBased>
				</KnowledgeRules>
			</System>
		</ModelType>
	</Autecology>
	<ContentDescription>
		<Description language="ENG">
			<text><![CDATA[Test
	Test]]></text>
		</Description>
	</ContentDescription>
	<Documentation>
		<reference author="Haasnoot, M. en Van de Wolfshaar, K.E." year="2006" title="Habitat analyse in het kader van de Planstudie/MER voor Krammer, Volkerak en Zoommeer. " journal="WL | Delft Hydraulics" identification="WL report Q4015"/>
		<reference author="Van de Wolfshaar, K.E., M. Haasnoot" year="2007" title="Toetsing dosis-effect relaties HABITAT. Pilot voor het Markermeer en de Voordelta." journal="WL | Delft Hydraulics" identification="WL-report Q4327">
			<html><![CDATA[http://public.deltares.nl/download/attachments/16384257/Van+de+Wolfshaar+en+Haasnoot+2007.pdf?version=1]]></html>
		</reference>
	</Documentation>
	<DataSources/>
</AutecologyXML>
