=== Deltares-research/KnowledgeRules/tool_adapters/Deltares_HABITAT/examples/AutecologyXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Knowledge Rules project ( Copyright under GPLv3 by Stichting Deltares ) -->
<schema xmlns:AutXML="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<element name="AutecologyXML" type="AutXML:AutecologyXMLConfigComplexType"/>
	<complexType name="AutecologyXMLConfigComplexType">
		<sequence>
			<element name="Topic" type="AutXML:TopicComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Autecology" type="AutXML:AutecologyComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="ContentDescription" type="AutXML:CDComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Documentation" type="AutXML:DocumentationComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="DataSources" type="AutXML:DataSourcesComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TopicComplexType">
		<choice>
			<element name="Species" type="AutXML:SpeciesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="WFDindicator" type="AutXML:WFDIComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="SpeciesComplexType">
		<sequence>
			<element name="EoLpagenr" type="AutXML:ExternalIntegerSimpleType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="LatName" type="string">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<choice>
				<element name="SpecCode" type="string" minOccurs="0">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="WFDIComplexType">
		<sequence>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="AutecologyComplexType">
		<sequence>
			<element name="ModelType" type="AutXML:ModelTypeComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ModelTypeComplexType">
		<sequence>
			<element name="System" type="AutXML:SystemComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="SystemComplexType">
		<sequence>
			<element name="Scope" type="AutXML:ScopeComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemDescription" type="AutXML:CDComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemFlowDiagrams" type="AutXML:SystemFlowDiagramsComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="KnowledgeRules" type="AutXML:KnowledgeRulesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ScopeComplexType">
		<sequence>
			<element name="SpatialScope" type="AutXML:SpatialScopeComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="TemporalScope" type="AutXML:TemporalScopeComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SpatialScopeComplexType">
		<sequence>
			<element name="GeoNames" type="AutXML:GeoNamesComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="GeoNamesComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="id" type="integer" use="required"/>
	</complexType>
	<complexType name="TemporalScopeComplexType">
		<sequence>
			<element name="StartDate" type="AutXML:dateType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="EndDate" type="AutXML:dateType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SystemFlowDiagramsComplexType">
		<sequence>
			<element name="FlowDiagram" type="AutXML:FlowDiagramComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FlowDiagramComplexType">
		<sequence>
			<element name="From" type="AutXML:LinkFromComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="KnowledgeRulesComplexType">
		<sequence>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element name="ResponseCurve" type="AutXML:ResponseCurveComplexType" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
				<element name="FormulaBased" type="AutXML:FormulaBasedComplexType" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="ResponseCurveComplexType">
		<sequence>
			<element name="type" type="AutXML:TypeSingleType" minOccurs="1" maxOccurs="1"/>
			<element name="layername" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="unit" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="statistic" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="description" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="author" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="date" type="AutXML:dateType" minOccurs="1" maxOccurs="1"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="1" maxOccurs="1"/>
			<choice>
				<element name="valuesScalar" type="AutXML:RCValuesScalarComplexType" minOccurs="1" maxOccurs="1"/>
				<element name="valuesCategorical" type="AutXML:RCValuesCategoricalComplexType" minOccurs="1" maxOccurs="1"/>
				<element name="valuesRangeCategorical" type="AutXML:RCValuesRangeCategoricalComplexType" minOccurs="1" maxOccurs="1"/>
				<element name="valuesRanges" type="AutXML:RCValuesRangesComplexType" minOccurs="1" maxOccurs="1"/>
			</choice>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="FormulaBasedComplexType">
		<sequence>
			<element name="layername" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="unit" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="statistic" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="description" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="author" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="date" type="AutXML:dateType" minOccurs="1" maxOccurs="1"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="1" maxOccurs="1"/>
			<element name="output" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="equation" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="Parameters" type="AutXML:FBParametersComplexType" minOccurs="1" maxOccurs="1"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ReferencesComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBParametersComplexType">
		<sequence>
			<element name="valuesConstant" type="AutXML:FBConstantValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="valuesScalar" type="AutXML:FBScalarValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesScalarComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterCategoricalRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangeCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangeCategoricalRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangesRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBConstantValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterConstantFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="constant"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="FBScalarValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="scalar"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterConstantFBComplexType">
		<attribute name="constantset" type="string" use="required"/>
		<attribute name="value" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarFBComplexType">
		<attribute name="min" type="string" use="required"/>
		<attribute name="max" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarRCComplexType">
		<attribute name="value" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterCategoricalRCComplexType">
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangeCategoricalRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangesRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="CDComplexType">
		<sequence>
			<element name="Description" type="AutXML:DescriptionComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DocumentationComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DataSourcesComplexType"/>
	<complexType name="CommonNamesComplexType">
		<sequence>
			<element name="Name" type="AutXML:NameComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="NameComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="DescriptionComplexType">
		<sequence>
			<element name="text" type="string"/>
		</sequence>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="LinkFromComplexType">
		<sequence>
			<element name="label" type="string"/>
			<element name="equation" type="AutXML:LinkEquationSimpleType"/>
			<element name="specific_equation" type="string" minOccurs="0"/>
			<element name="To" type="string" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<simpleType name="LinkEquationSimpleType">
		<restriction base="string">
			<enumeration value="average"/>
			<enumeration value="min"/>
			<enumeration value="max"/>
			<enumeration value="geometric_average"/>
			<enumeration value="specific"/>
		</restriction>
	</simpleType>
	<complexType name="ReferenceComplexType">
		<choice>
			<element name="html" type="string" minOccurs="0"/>
		</choice>
		<attribute name="author" type="string" use="required"/>
		<attribute name="year" type="string" use="required"/>
		<attribute name="title" type="string" use="required"/>
		<attribute name="journal" type="string" use="required"/>
		<attribute name="identification" type="string" use="required"/>
	</complexType>
	<complexType name="DateTimeComplexType">
		<attribute name="date" type="AutXML:dateType" use="required"/>
	</complexType>
	<simpleType name="dateType">
		<restriction base="date">
			<pattern value="\d\d\d\d-\d\d-\d\d"/>
		</restriction>
	</simpleType>
	<simpleType name="TypeSingleType">
		<restriction base="string">
			<enumeration value="scalar"/>
			<enumeration value="categorical"/>
			<enumeration value="range / categorical"/>
			<enumeration value="ranges"/>
		</restriction>
	</simpleType>
	<simpleType name="ExternalIntegerSimpleType">
		<union memberTypes="integer">
			<simpleType>
				<restriction base="string">
					<pattern value="[$][a-zA-Z0-9.()*/+-_]+[$]"/>
				</restriction>
			</simpleType>
		</union>
	</simpleType>
</schema>

=== Deltares-research/KnowledgeRules/_knowledgerules/species/Fish/Petromyzon marinus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by ICT (Stichting Deltares) -->
<AutecologyXML xmlns="http://www.wldelft.nl/fews" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wldelft.nl/fews ../../../XMLSchema/AutecologyXML.xsd">
	<Topic>
		<Species>
			<EoLpagenr>46582331</EoLpagenr>
			<LatName>Petromyzon marinus</LatName>
			<CommonNames>
				<Name name="Zeeprik" language="NL"/>
			</CommonNames>
			<SpecCode/>
		</Species>
	</Topic>
	<Autecology>
		<ModelType name="HSI">
			<System name="adult">
				<Scope>
					<SpatialScope>
						<GeoNames name="Netherlands" id="2750405"/>
					</SpatialScope>
					<TemporalScope>
						<StartDate>2004-01-01</StartDate>
						<EndDate>2004-01-01</EndDate>
					</TemporalScope>
				</Scope>
				<SystemDescription>
					<Description language="NL">
						<text><![CDATA[<h1 id="Zeeprik-Petronyzonmarinus-Onzekerheidenvalidatie">Onzekerheid en validatie</h1>

<p><img class="emoticon emoticon-warning" src="./Zeeprik - Petronyzon marinus - HABITAT - Spatial analysis tool - Deltares Public Wiki_files/warning.svg" data-emoticon-name="warning" alt="(warning)">&nbsp;Deze dosis-effect relaties zijn niet gevalideerd.</p>

<h1 id="Zeeprik-Petronyzonmarinus-Toepasbaarheid">Toepasbaarheid</h1>

<p>De dosis-effect relatie voor trek is van toepassing voor rivieren in Nederland. De dosis-effect relaties voor het paaigebied zijn niet voor Nederland van toepassing.</p>

<h1 id="Zeeprik-Petronyzonmarinus-Voorbeeldproject">Voorbeeld project</h1>

<p>Voor deze dosis-effect relaties is geen voorbeeldprojekt beschikbaar.</p>]]></text>
					</Description>
				</SystemDescription>
				<SystemFlowDiagrams>
					<FlowDiagram name="HGI">
						<From name="Habitat_quality">
							<label>"Habitat_quality"</label>
							<equation>min</equation>
							<To>Migration_habitat_quality</To>
							<To>Spawning_habitat_quality</To>
						</From>
						<From name="Migration_habitat_quality">
							<label>"Migration_habitat_quality"</label>
							<equation>min</equation>
							<To>Barriers_upwards</To>
							<To>Barriers_downwards</To>
						</From>
						<From name="Spawning_habitat_quality">
							<label>"Spawning_habitat_quality"</label>
							<equation>min</equation>
							<To>Substrate_juveniles</To>
							<To>Flow_velocity_spawning</To>
							<To>Substrate_spawning</To>
						</From>
					</FlowDiagram>
				</SystemFlowDiagrams>
				<KnowledgeRules>
					<ResponseCurve name="Barriers_upwards">
						<type>categorical</type>
						<layername>"Barriers_upwards"</layername>
						<unit>"category"</unit>
						<statistic>minimum</statistic>
						<description>"Presence of barriers during stream upward migration"</description>
						<author>"Marjolijn Haasnoot"</author>
						<date>2009-01-01</date>
						<references>
							<reference author="Expert Judgement Jan Kranenbarg" year="" title="" journal="" identification=""/>
						</references>
						<valuesCategorical>
							<parameter cat="sluice" HSI="0.5"/>
							<parameter cat="shipping lock + weir + fish ladder" HSI="0.7"/>
							<parameter cat="
shipping lock + weir + hydroelectric power station + fish ladder" HSI="0.7"/>
						</valuesCategorical>
					</ResponseCurve>	
					<ResponseCurve name="Barriers_downwards">
						<type>categorical</type>
						<layername>"Barriers_downwards"</layername>
						<unit>"category"</unit>
						<statistic>minimum</statistic>
						<description>"Presence of barriers during stream downward migration"</description>
						<author>"Marjolijn Haasnoot"</author>
						<date>2009-01-01</date>
						<references>
							<reference author="Expert Judgement Jan Kranenbarg" year="" title="" journal="" identification=""/>
						</references>
						<valuesCategorical>
							<parameter cat="sluice" HSI="0.8"/>
							<parameter cat="shipping lock + weir + fish ladder" HSI="1.0"/>
							<parameter cat="
shipping lock + weir + hydroelectric power station + fish ladder" HSI="0.7"/>
						</valuesCategorical>
					</ResponseCurve>	
					<ResponseCurve name="Substrate_juveniles">
						<type>categorical</type>
						<layername>"Substrate_juveniles"</layername>
						<unit>"categorical"</unit>
						<statistic>average</statistic>
						<description>"Type of sediment expressed in categories"</description>
						<author>"Marjolein Haasnoot"</author>
						<date>2009-01-01</date>
						<references>
							<reference author="Janssen, J.A.M. en Schaminee, J.H.J." year="2004" title="" journal="" identification=""/>
						</references>
						<valuesCategorical>
							<parameter cat="Silt" HSI="1.0"/>
							<parameter cat="Silt/sand" HSI="1.0"/>
							<parameter cat="Fine/coarse sand" HSI="0.5"/>							
							<parameter cat="Coarse sand/pebbles" HSI="0.1"/>							
							<parameter cat="Pebbles" HSI="0.0"/>
						</valuesCategorical>
					</ResponseCurve>
					<ResponseCurve name="Flow_velocity_spawning">
						<type>range / categorical</type>
						<layername>Flow_velocity_spawning</layername>
						<unit>m/s</unit>
						<statistic>average</statistic>
						<description>Flow_velocity in the spawning area in meters per second</description>
						<author>"Marjolein Haasnoot"</author>
						<date>2009-01-01</date>
						<references>
							<reference author="Janssen, J.A.M. en Schaminee, J.H.J." year="2004" title="" journal="" identification=""/>
						</references>
						<valuesRangeCategorical>
							<parameter rangemin="0" rangemax="1" cat="0 - 1" HSI="0.0"/>
							<parameter rangemin="1" rangemax="2" cat="1 - 2" HSI="1.0"/>
							<parameter rangemin="2" rangemax="999999" cat="> 2" HSI="0.0"/>
						</valuesRangeCategorical>
					</ResponseCurve>
					<ResponseCurve name="Substrate_spawning">
						<type>categorical</type>
						<layername>"Substrate_spawning"</layername>
						<unit>"categorical"</unit>
						<statistic>average</statistic>
						<description>"Availability of pebbles in the spawning area"</description>
						<author>"Marjolein Haasnoot"</author>
						<date>2009-01-01</date>
						<references>
							<reference author="Janssen, J.A.M. en Schaminee, J.H.J." year="2004" title="" journal="" identification=""/>
							<reference author="Rivierprik - Lampetra fluviatilis" year="" title="" journal="" identification=""/>
						</references>
						<valuesCategorical>
							<parameter cat="None" HSI="0.0"/>
							<parameter cat="Few" HSI="0.1"/>
							<parameter cat="Moderate" HSI="0.35"/>
							<parameter cat="Reasonable" HSI="0.65"/>
							<parameter cat="Many" HSI="1.0"/>
						</valuesCategorical>
					</ResponseCurve>
				</KnowledgeRules>
			</System>
		</ModelType>
	</Autecology>
	<ContentDescription>
		<Description language="NL">
			<text><![CDATA[<h3 id="Zeeprik-Petronyzonmarinus-Algemeenvoorkomen">Algemeen voorkomen</h3>

<p>De Zeeprik (Petromyzon marinus) is een vis uit de familie der Prikachtigen (Petromyzontidae), die deel uitmaakt van de Rondbekken. In plaats van kaken bezitten prikken rondom de bek een zuigschijf, die bezet is met tanden. De normaal bij vissen aanwezige buik- en borstvinnen ontbreken, maar ze hebben wel een (doorgaans tweedelige) rugvin die ver achter op het lichaam is geplaatst. Op grond van enkele afwijkende kenmerken vormen rondbekken een eigen klasse. Alle andere zoetwatervissen in Nederland behoren tot de beenvissen; kraakbeenvissen vormen een derde groep. De Zeeprik is vuilwit tot grijswit van kleur en heeft een opvallend gemarmerd vlekkenpatroon. De ronde palingachtige vorm is naar achteren toe ietwat zijdelings samengedrukt. De Zeeprik bereikt een lengte tot 100 cm, waarmee ze de grootste prikkensoort in Europa is. De lengte, kleur, vlekkentekening en plaatsing van de tanden in de zuigbek onderscheiden de soort van de andere prikken <a href="https://publicwiki.deltares.nl/display/HBTHOME/Zeeprik+-+Petronyzon+marinus#Zeeprik-Petronyzonmarinus-1">#1</a>.<br>
De Zeeprik heeft een noordatlantisch areaal (Noord-Amerika, Europa). In Europa leeft hij verspreid langs de kusten en in de grote rivieren van Noord-Rusland tot in de Middellandse Zee. De Zeeprik gebruikt ons land alleen als doortrekgebied op weg naar geschikte paaiplaatsen halverwege Duitsland <a href="https://publicwiki.deltares.nl/display/HBTHOME/Zeeprik+-+Petronyzon+marinus#Zeeprik-Petronyzonmarinus-2">#2</a>.</p>

<h3 id="Zeeprik-Petronyzonmarinus-Voedselhabitatenstrategie">Voedselhabitat en strategie</h3>

<p>Parasitair als adult, larven voeden zich met algen en plantaardig materiaal <a href="https://publicwiki.deltares.nl/display/HBTHOME/Zeeprik+-+Petronyzon+marinus#Zeeprik-Petronyzonmarinus-2">#2</a>.</p>

<h3 id="Zeeprik-Petronyzonmarinus-Reproductieenmigratie">Reproductie en migratie</h3>

<p>Anadrome trekvis. De paaigronden liggen in de midden en bovenlopen van de grote rivieren. Het zijn ondiepe plekken (circa 50 cm diep) met hoge stroomsnelheden (1-2 m/s) en een stenige zonverwarmde bodem. De trek vindt plaats in feb-jun <a href="https://publicwiki.deltares.nl/display/HBTHOME/Zeeprik+-+Petronyzon+marinus#Zeeprik-Petronyzonmarinus-2">#2</a>.</p>

<h3 id="Zeeprik-Petronyzonmarinus-Leeftijdenmortaliteit">Leeftijd en mortaliteit</h3>

<p>Larven leven 5 tot 8 jaar in een modderbank (zoetwater) en voeden zich daar met algen, plantenresten en ander organisch materiaal. Volwassen blijven zo'n drie jaar op zee voor ze naar de paaigronden gaan waar ze meestal na de voortplanting sterven <a href="https://publicwiki.deltares.nl/display/HBTHOME/Zeeprik+-+Petronyzon+marinus#Zeeprik-Petronyzonmarinus-2">#2</a>.</p>]]></text>
		</Description>
	</ContentDescription>
	<Documentation>
		<reference author="" year="" title="http://www.minlnv.nl/natura2000" journal="" identification=""/>
		<reference author="Janssen, J.A.M. en Schaminee, J.H.J." year="2004" title="Europese natuur in Nederland; soorten van de Habitat richtlijn." journal="" identification="2004"/>
	</Documentation>
	<DataSources/>
</AutecologyXML>
