=== Deltares-research/KnowledgeRules/tool_adapters/Deltares_HABITAT/examples/AutecologyXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Knowledge Rules project ( Copyright under GPLv3 by Stichting Deltares ) -->
<schema xmlns:AutXML="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<element name="AutecologyXML" type="AutXML:AutecologyXMLConfigComplexType"/>
	<complexType name="AutecologyXMLConfigComplexType">
		<sequence>
			<element name="Topic" type="AutXML:TopicComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Autecology" type="AutXML:AutecologyComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="ContentDescription" type="AutXML:CDComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Documentation" type="AutXML:DocumentationComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="DataSources" type="AutXML:DataSourcesComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TopicComplexType">
		<choice>
			<element name="Species" type="AutXML:SpeciesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="WFDindicator" type="AutXML:WFDIComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="SpeciesComplexType">
		<sequence>
			<element name="EoLpagenr" type="AutXML:ExternalIntegerSimpleType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="LatName" type="string">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<choice>
				<element name="SpecCode" type="string" minOccurs="0">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="WFDIComplexType">
		<sequence>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="AutecologyComplexType">
		<sequence>
			<element name="ModelType" type="AutXML:ModelTypeComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ModelTypeComplexType">
		<sequence>
			<element name="System" type="AutXML:SystemComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="SystemComplexType">
		<sequence>
			<element name="Scope" type="AutXML:ScopeComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemDescription" type="AutXML:CDComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemFlowDiagrams" type="AutXML:SystemFlowDiagramsComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="KnowledgeRules" type="AutXML:KnowledgeRulesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ScopeComplexType">
		<sequence>
			<element name="SpatialScope" type="AutXML:SpatialScopeComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="TemporalScope" type="AutXML:TemporalScopeComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SpatialScopeComplexType">
		<sequence>
			<element name="GeoNames" type="AutXML:GeoNamesComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="GeoNamesComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="id" type="integer" use="required"/>
	</complexType>
	<complexType name="TemporalScopeComplexType">
		<sequence>
			<element name="StartDate" type="AutXML:dateType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="EndDate" type="AutXML:dateType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SystemFlowDiagramsComplexType">
		<sequence>
			<element name="FlowDiagram" type="AutXML:FlowDiagramComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FlowDiagramComplexType">
		<sequence>
			<element name="From" type="AutXML:LinkFromComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="KnowledgeRulesComplexType">
		<sequence>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element name="ResponseCurve" type="AutXML:ResponseCurveComplexType" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
				<element name="FormulaBased" type="AutXML:FormulaBasedComplexType" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="ResponseCurveComplexType">
		<sequence>
			<element name="type" type="AutXML:TypeSingleType" minOccurs="1" maxOccurs="1"/>
			<element name="layername" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="unit" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="statistic" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="description" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="author" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="date" type="AutXML:dateType" minOccurs="1" maxOccurs="1"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="1" maxOccurs="1"/>
			<choice>
				<element name="valuesScalar" type="AutXML:RCValuesScalarComplexType" minOccurs="1" maxOccurs="1"/>
				<element name="valuesCategorical" type="AutXML:RCValuesCategoricalComplexType" minOccurs="1" maxOccurs="1"/>
				<element name="valuesRangeCategorical" type="AutXML:RCValuesRangeCategoricalComplexType" minOccurs="1" maxOccurs="1"/>
				<element name="valuesRanges" type="AutXML:RCValuesRangesComplexType" minOccurs="1" maxOccurs="1"/>
			</choice>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="FormulaBasedComplexType">
		<sequence>
			<element name="layername" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="unit" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="statistic" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="description" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="author" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="date" type="AutXML:dateType" minOccurs="1" maxOccurs="1"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="1" maxOccurs="1"/>
			<element name="output" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="equation" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="Parameters" type="AutXML:FBParametersComplexType" minOccurs="1" maxOccurs="1"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ReferencesComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBParametersComplexType">
		<sequence>
			<element name="valuesConstant" type="AutXML:FBConstantValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="valuesScalar" type="AutXML:FBScalarValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesScalarComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterCategoricalRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangeCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangeCategoricalRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangesRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBConstantValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterConstantFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="constant"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="FBScalarValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="scalar"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterConstantFBComplexType">
		<attribute name="constantset" type="string" use="required"/>
		<attribute name="value" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarFBComplexType">
		<attribute name="min" type="string" use="required"/>
		<attribute name="max" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarRCComplexType">
		<attribute name="value" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterCategoricalRCComplexType">
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangeCategoricalRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangesRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="CDComplexType">
		<sequence>
			<element name="Description" type="AutXML:DescriptionComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DocumentationComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DataSourcesComplexType"/>
	<complexType name="CommonNamesComplexType">
		<sequence>
			<element name="Name" type="AutXML:NameComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="NameComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="DescriptionComplexType">
		<sequence>
			<element name="text" type="string"/>
		</sequence>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="LinkFromComplexType">
		<sequence>
			<element name="label" type="string"/>
			<element name="equation" type="AutXML:LinkEquationSimpleType"/>
			<element name="specific_equation" type="string" minOccurs="0"/>
			<element name="To" type="string" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<simpleType name="LinkEquationSimpleType">
		<restriction base="string">
			<enumeration value="average"/>
			<enumeration value="min"/>
			<enumeration value="max"/>
			<enumeration value="geometric_average"/>
			<enumeration value="specific"/>
		</restriction>
	</simpleType>
	<complexType name="ReferenceComplexType">
		<choice>
			<element name="html" type="string" minOccurs="0"/>
		</choice>
		<attribute name="author" type="string" use="required"/>
		<attribute name="year" type="string" use="required"/>
		<attribute name="title" type="string" use="required"/>
		<attribute name="journal" type="string" use="required"/>
		<attribute name="identification" type="string" use="required"/>
	</complexType>
	<complexType name="DateTimeComplexType">
		<attribute name="date" type="AutXML:dateType" use="required"/>
	</complexType>
	<simpleType name="dateType">
		<restriction base="date">
			<pattern value="\d\d\d\d-\d\d-\d\d"/>
		</restriction>
	</simpleType>
	<simpleType name="TypeSingleType">
		<restriction base="string">
			<enumeration value="scalar"/>
			<enumeration value="categorical"/>
			<enumeration value="range / categorical"/>
			<enumeration value="ranges"/>
		</restriction>
	</simpleType>
	<simpleType name="ExternalIntegerSimpleType">
		<union memberTypes="integer">
			<simpleType>
				<restriction base="string">
					<pattern value="[$][a-zA-Z0-9.()*/+-_]+[$]"/>
				</restriction>
			</simpleType>
		</union>
	</simpleType>
</schema>

=== Deltares-research/KnowledgeRules/_knowledgerules/species/Macrophytes/Phragmites australis.xml
<?xml version="1.0" encoding="UTF-8"?>
<AutecologyXML xmlns="http://www.wldelft.nl/fews" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wldelft.nl/fews ../../../XMLSchema/AutecologyXML.xsd">
	<Topic>
		<Species>
			<EoLpagenr>1114576</EoLpagenr>
			<LatName>Phragmites australis</LatName>
			<CommonNames>
				<Name name = "Riet" language = "NL"/>
			</CommonNames>
			<SpecCode/>
		</Species>
		</Topic>
	<Autecology>
		<ModelType name="HSI">
			<System name="adult">
				<Scope>
					<SpatialScope>
						<GeoNames name="Netherlands" id="2750405"/>
					</SpatialScope>
					<TemporalScope>
						<StartDate>1995-01-01</StartDate>
						<EndDate>2002-01-01</EndDate>
					</TemporalScope>
				</Scope>
				<SystemDescription>
					<Description language="NL">
					<text><![CDATA[<h1 id="Riet-Phragmitesaustralis-Onzekerheidenvalidatie">Onzekerheid en validatie</h1>

<p>Deze dosis-effect relaties zijn niet gevalideerd</p>

<h1 id="Riet-Phragmitesaustralis-Toepasbaarheid">Toepasbaarheid</h1>

<p>Deze dosis-effect relaties beschrijven nog niet een model. Deze dosis-effect relaties zijn , in zoverre, toepasbaar op zoete wateren in Nederland.</p>

<h1 id="Riet-Phragmitesaustralis-Voorbeeldproject">Voorbeeld project</h1>

<p>Er is geen voorbeeld project.</p>]]></text>
					</Description>
				</SystemDescription>
				<SystemFlowDiagrams>
					<FlowDiagram name="HGI">
						<From name="Habitat_quality">
							<label>"Habitat_quality"</label>
							<equation>min</equation>
							<To>Salinity_germination</To>
							<To>Salinity_seedling</To>
							<To>Salinity_adult</To>
							<To>Grazing_of_bank_vegetation</To>
						</From>
					</FlowDiagram>
				</SystemFlowDiagrams>
				<KnowledgeRules>		
					<ResponseCurve name="Salinity_germination">
						<type>scalar</type>
						<layername>"Salinity_germination"</layername>
						<unit>"gCl/l"</unit>
						<statistic>average</statistic>
						<description>"Chloride concentration during germination in milligrams chloride per liter"</description>
						<author>"Valesca Harezlak"</author>
						<date>2013-01-15</date>
						<references>
							<reference author="Ter Heerdt, G." year="1995" title="" journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0" HSI="1.0"/>
							<parameter value="9" HSI="1.0"/>
							<parameter value="12" HSI="0.0"/>
							<parameter value="23" HSI="0.0"/>
						</valuesScalar>
					</ResponseCurve>
					<ResponseCurve name="Salinity_seedling">
						<type>scalar</type>
						<layername>"Salinity_seedling"</layername>
						<unit>"gCl/l"</unit>
						<statistic>average</statistic>
						<description>"Chloride concentration during the seedling life stage in milligrams chloride per liter"</description>
						<author>"Valesca Harezlak"</author>
						<date>2013-01-15</date>
						<references>
							<reference author="Ter Heerdt, G." year="1995" title="" journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0" HSI="1.0"/>
							<parameter value="5" HSI="1.0"/>
							<parameter value="16" HSI="0.0"/>
							<parameter value="23" HSI="0.0"/>
						</valuesScalar>
					</ResponseCurve>
					<ResponseCurve name="Salinity_adult">
						<type>scalar</type>
						<layername>"Salinity_adult"</layername>
						<unit>"gCl/l"</unit>
						<statistic>average</statistic>
						<description>"Chloride concentration during the adult life stage in milligrams chloride per liter"</description>
						<author>"Valesca Harezlak"</author>
						<date>2013-01-15</date>
						<references>
							<reference author="Ter Heerdt, G." year="1995" title="" journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0" HSI="1.0"/>
							<parameter value="12" HSI="1.0"/>
							<parameter value="16" HSI="0.0"/>
							<parameter value="23" HSI="0.0"/>
						</valuesScalar>
					</ResponseCurve>
					<ResponseCurve name="Grazing_of_bank_vegetation">
						<type>scalar</type>
						<layername>"Grazing_of_bank_vegetation"</layername>
						<unit>"m"</unit>
						<statistic>average</statistic>
						<description>"Waterdepth in meters"</description>
						<author>"Valesca Harezlak"</author>
						<date>2013-01-15</date>
						<references>
							<reference author="" year="" title="" journal="" identification=""/>
						</references>
						<valuesScalar>
							<parameter value="0" HSI="1.0"/>
							<parameter value="0.5" HSI="1.0"/>
							<parameter value="0.5" HSI="0.0"/>
							<parameter value="1" HSI="0.0"/>
						</valuesScalar>
					</ResponseCurve>
				</KnowledgeRules>
			</System>
		</ModelType>
	</Autecology>
	<ContentDescription>
		<Description language="NL"><text><![CDATA[<h3 id="Riet-Phragmitesaustralis-Algemeenvoorkomen">Algemeen voorkomen</h3>

<p>Riet behoort tot de familie van de grassen en is tevens de grootste van deze familie die in de Nederland van nature voorkomt. De plant is vaak te vinden aan de waterkant, maar ook in natte bodems van beek en rivierdalen doet deze plant het goed. Riet kan zich op 3 manieren verbreiden: door middel van zaad, door middel van diep in de bodem doordringende wortelstokken en door forse bovengrondse uitlopers <a href="https://publicwiki.deltares.nl/display/HBTHOME/Riet+-+Phragmites+australis#Riet-Phragmitesaustralis-2">#2</a> en <a href="https://publicwiki.deltares.nl/display/HBTHOME/Riet+-+Phragmites+australis#Riet-Phragmitesaustralis-3">#3</a>. Riet is een helofyt en kan voorkomen in zuurstofarme bodems. Door middel van luchtgangen via de halmen zorgt riet ervoor dat er zuurstof bij de wortels komt.</p>

<p>Aan het einde van de herfst als de winter aanvangt, sterft het bovengrondse gedeelte af met uitzondering van de stijve stengels. Als riet onder het watervlak gemaaid wordt sterft riet af doordat de luchtholten vollopen en hierdoor verdrinkt <a href="https://publicwiki.deltares.nl/display/HBTHOME/Riet+-+Phragmites+australis#Riet-Phragmitesaustralis-3">#3</a>. Riet bloeit van juli tot oktober. De pollen worden met de wind meegevoerd en na bevruchting ontstaat er zaad waaruit, bij kieming, nieuwe rietplanten kunnen ontstaan <a href="https://publicwiki.deltares.nl/display/HBTHOME/Riet+-+Phragmites+australis#Riet-Phragmitesaustralis-3">#3</a>. </p>

<h3 id="Riet-Phragmitesaustralis-Milieurandvoorwaarden">Milieurandvoorwaarden</h3>

<p>Riet blijkt nog bij hoge zoutgehalten tot ontkieming te komen <a href="https://publicwiki.deltares.nl/display/HBTHOME/Riet+-+Phragmites+australis#Riet-Phragmitesaustralis-1">#1</a>. Ganzen kunnen een grote begrazingsdruk uitoefenen op riet dat in water tot ontwikkeling is gekomen. Tot een diepte van 50 cm kunnen de ganzen het riet begrazen <a href="https://publicwiki.deltares.nl/display/HBTHOME/Riet+-+Phragmites+australis#Riet-Phragmitesaustralis-2">#2</a>.</p>

<h3 id="Riet-Phragmitesaustralis-Beheerenontwikkelingskansen">Beheer en ontwikkelingskansen</h3>

<p>-</p>]]></text>
		</Description>
	</ContentDescription>
	<Documentation>
		<reference author="Ter Heerdt, G." year="1995" title="Planten in de Peiling: Literatuuronderzoek naar de invloed van het zoutgehalte in de bodem op de ontwikkeling van helofyten." journal="" identification="Directoraat-generaalRijkswaterstaat, Riza Notanr. 95.041, Laboratorium voor Plantenoecologie, Rijksuniversiteit Groningen, Lelystad, februari 1995"/>
		<reference author="Daling, J., Zijlstra, M., Van Manen, H.A." year="" title= "Invloed van waterpeil en begrazing op de ontwikkeling van oevervegetatie." journal="" identification="RIZA werkdocument 2002.122X, Rijksintituut voor Integraal Zoetwaterbeheer en Afvalwaterbehandeling.2002"/>
		<reference author="" year="" title= "www.floravannederland.nl (Riet)" journal="" identification="18 december 2012"/>
	</Documentation>
	<DataSources/>
</AutecologyXML>
