=== Deltares-research/KnowledgeRules/tool_adapters/Deltares_HABITAT/examples/AutecologyXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Knowledge Rules project ( Copyright under GPLv3 by Stichting Deltares ) -->
<schema xmlns:AutXML="http://www.wldelft.nl/fews" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" targetNamespace="http://www.wldelft.nl/fews" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<element name="AutecologyXML" type="AutXML:AutecologyXMLConfigComplexType"/>
	<complexType name="AutecologyXMLConfigComplexType">
		<sequence>
			<element name="Topic" type="AutXML:TopicComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Autecology" type="AutXML:AutecologyComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="ContentDescription" type="AutXML:CDComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="Documentation" type="AutXML:DocumentationComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="DataSources" type="AutXML:DataSourcesComplexType" minOccurs="0">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="TopicComplexType">
		<choice>
			<element name="Species" type="AutXML:SpeciesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="WFDindicator" type="AutXML:WFDIComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</choice>
	</complexType>
	<complexType name="SpeciesComplexType">
		<sequence>
			<element name="EoLpagenr" type="AutXML:ExternalIntegerSimpleType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="LatName" type="string">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<choice>
				<element name="SpecCode" type="string" minOccurs="0">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="WFDIComplexType">
		<sequence>
			<element name="CommonNames" type="AutXML:CommonNamesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="AutecologyComplexType">
		<sequence>
			<element name="ModelType" type="AutXML:ModelTypeComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="ModelTypeComplexType">
		<sequence>
			<element name="System" type="AutXML:SystemComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="SystemComplexType">
		<sequence>
			<element name="Scope" type="AutXML:ScopeComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemDescription" type="AutXML:CDComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="SystemFlowDiagrams" type="AutXML:SystemFlowDiagramsComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="KnowledgeRules" type="AutXML:KnowledgeRulesComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ScopeComplexType">
		<sequence>
			<element name="SpatialScope" type="AutXML:SpatialScopeComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="TemporalScope" type="AutXML:TemporalScopeComplexType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SpatialScopeComplexType">
		<sequence>
			<element name="GeoNames" type="AutXML:GeoNamesComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="GeoNamesComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="id" type="integer" use="required"/>
	</complexType>
	<complexType name="TemporalScopeComplexType">
		<sequence>
			<element name="StartDate" type="AutXML:dateType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
			<element name="EndDate" type="AutXML:dateType">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="SystemFlowDiagramsComplexType">
		<sequence>
			<element name="FlowDiagram" type="AutXML:FlowDiagramComplexType" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
	</complexType>
	<complexType name="FlowDiagramComplexType">
		<sequence>
			<element name="From" type="AutXML:LinkFromComplexType" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="KnowledgeRulesComplexType">
		<sequence>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element name="ResponseCurve" type="AutXML:ResponseCurveComplexType" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
				<element name="FormulaBased" type="AutXML:FormulaBasedComplexType" minOccurs="0" maxOccurs="unbounded">
					<annotation>
						<documentation>Optional provision of input files, if provided ALL relevant input files needs to be defined, if not, the program will check for files with default naming in the current working folder</documentation>
					</annotation>
				</element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="ResponseCurveComplexType">
		<sequence>
			<element name="type" type="AutXML:TypeSingleType" minOccurs="1" maxOccurs="1"/>
			<element name="layername" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="unit" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="statistic" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="description" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="author" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="date" type="AutXML:dateType" minOccurs="1" maxOccurs="1"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="1" maxOccurs="1"/>
			<choice>
				<element name="valuesScalar" type="AutXML:RCValuesScalarComplexType" minOccurs="1" maxOccurs="1"/>
				<element name="valuesCategorical" type="AutXML:RCValuesCategoricalComplexType" minOccurs="1" maxOccurs="1"/>
				<element name="valuesRangeCategorical" type="AutXML:RCValuesRangeCategoricalComplexType" minOccurs="1" maxOccurs="1"/>
				<element name="valuesRanges" type="AutXML:RCValuesRangesComplexType" minOccurs="1" maxOccurs="1"/>
			</choice>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="FormulaBasedComplexType">
		<sequence>
			<element name="layername" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="unit" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="statistic" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="description" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="author" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="date" type="AutXML:dateType" minOccurs="1" maxOccurs="1"/>
			<element name="references" type="AutXML:ReferencesComplexType" minOccurs="1" maxOccurs="1"/>
			<element name="output" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="equation" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="Parameters" type="AutXML:FBParametersComplexType" minOccurs="1" maxOccurs="1"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="ReferencesComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBParametersComplexType">
		<sequence>
			<element name="valuesConstant" type="AutXML:FBConstantValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
			<element name="valuesScalar" type="AutXML:FBScalarValuesComplexType" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesScalarComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterCategoricalRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangeCategoricalComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangeCategoricalRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="RCValuesRangesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterRangesRCComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="FBConstantValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterConstantFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="constant"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="FBScalarValuesComplexType">
		<sequence>
			<element name="parameter" type="AutXML:ParameterScalarFBComplexType" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="dataname" type="string" use="required"/>
		<attribute name="type" type="string" use="required" fixed="scalar"/>
		<attribute name="unit" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterConstantFBComplexType">
		<attribute name="constantset" type="string" use="required"/>
		<attribute name="value" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarFBComplexType">
		<attribute name="min" type="string" use="required"/>
		<attribute name="max" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterScalarRCComplexType">
		<attribute name="value" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterCategoricalRCComplexType">
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangeCategoricalRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="cat" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="ParameterRangesRCComplexType">
		<attribute name="rangemin" type="string" use="required"/>
		<attribute name="rangemax" type="string" use="required"/>
		<attribute name="HSI" type="string" use="required"/>
	</complexType>
	<complexType name="CDComplexType">
		<sequence>
			<element name="Description" type="AutXML:DescriptionComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DocumentationComplexType">
		<sequence>
			<element name="reference" type="AutXML:ReferenceComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="DataSourcesComplexType"/>
	<complexType name="CommonNamesComplexType">
		<sequence>
			<element name="Name" type="AutXML:NameComplexType" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	<complexType name="NameComplexType">
		<attribute name="name" type="string" use="required"/>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="DescriptionComplexType">
		<sequence>
			<element name="text" type="string"/>
		</sequence>
		<attribute name="language" type="string" use="required"/>
	</complexType>
	<complexType name="LinkFromComplexType">
		<sequence>
			<element name="label" type="string"/>
			<element name="equation" type="AutXML:LinkEquationSimpleType"/>
			<element name="specific_equation" type="string" minOccurs="0"/>
			<element name="To" type="string" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<simpleType name="LinkEquationSimpleType">
		<restriction base="string">
			<enumeration value="average"/>
			<enumeration value="min"/>
			<enumeration value="max"/>
			<enumeration value="geometric_average"/>
			<enumeration value="specific"/>
		</restriction>
	</simpleType>
	<complexType name="ReferenceComplexType">
		<choice>
			<element name="html" type="string" minOccurs="0"/>
		</choice>
		<attribute name="author" type="string" use="required"/>
		<attribute name="year" type="string" use="required"/>
		<attribute name="title" type="string" use="required"/>
		<attribute name="journal" type="string" use="required"/>
		<attribute name="identification" type="string" use="required"/>
	</complexType>
	<complexType name="DateTimeComplexType">
		<attribute name="date" type="AutXML:dateType" use="required"/>
	</complexType>
	<simpleType name="dateType">
		<restriction base="date">
			<pattern value="\d\d\d\d-\d\d-\d\d"/>
		</restriction>
	</simpleType>
	<simpleType name="TypeSingleType">
		<restriction base="string">
			<enumeration value="scalar"/>
			<enumeration value="categorical"/>
			<enumeration value="range / categorical"/>
			<enumeration value="ranges"/>
		</restriction>
	</simpleType>
	<simpleType name="ExternalIntegerSimpleType">
		<union memberTypes="integer">
			<simpleType>
				<restriction base="string">
					<pattern value="[$][a-zA-Z0-9.()*/+-_]+[$]"/>
				</restriction>
			</simpleType>
		</union>
	</simpleType>
</schema>

=== Deltares-research/KnowledgeRules/_knowledgerules/species/Mammals/Phocaena_phocaena.xml
<AutecologyXML xmlns="http://www.wldelft.nl/fews" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.wldelft.nl/fews ../../../XMLSchema/AutecologyXML.xsd">
	<Topic>
		<Species>
			<EoLpagenr>49941532</EoLpagenr>
			<LatName>Phocaena phocaena</LatName>
			<CommonNames>
				<Name name="Bruinvis" language="NL"/>
			</CommonNames>
			<SpecCode/>
		</Species>
	</Topic>
	<Autecology>
		<ModelType name="HSI">
			<System name="adult">
				<Scope>
					<SpatialScope>
						<GeoNames name="Netherlands" id="2750405"/>
					</SpatialScope>
					<TemporalScope>
						<StartDate>2008-01-01</StartDate>
						<EndDate>2009-01-01</EndDate>
					</TemporalScope>
				</Scope>
				<SystemDescription>
					<Description language="NL">
						<text>&lt;h1 id="Bruinvis-Phocaenaphocaena-Onzekerheidenvalidatie"&gt;Onzekerheid en validatie&lt;/h1&gt;&lt;p&gt;&lt;img class="emoticon emoticon-warning" src="./Bruinvis - Phocaena phocaena - HABITAT - Spatial analysis tool - Deltares Public Wiki_files/warning.svg" data-emoticon-name="warning" alt="(warning)"&gt; Deze dosis-effect relatie is niet gevalideerd.&lt;/p&gt;&lt;h1 id="Bruinvis-Phocaenaphocaena-Toepasbaarheid"&gt;Toepasbaarheid&lt;/h1&gt;&lt;p&gt;Er is weinig informatie beschikbaar over de Bruinvis om dosis-effect relaties op te baseren. Zo is het gebruik van zogenaamde visserij met staand want (waarbij de dieren in de netten verstrikt raken en verdrinken) zeer waarschijnlijk de oorzaak van de achteruitgang van de Bruinvis in de Noordzee &lt;a href="https://publicwiki.deltares.nl/display/HBTHOME/Bruinvis+-+Phocaena+phocaena#Bruinvis-Phocaenaphocaena-1"&gt;#1&lt;/a&gt;. Het maken van een kwantitatieve dosis-effect relatie met betrekking tot visserij is echter lastig. Ook kan watervervuiling een bedreiging vormen voor de Bruinvis. Milieuvervuilende stoffen zijn gemeten in bruinvissen, waarschijnlijk omdat ze voornamelijk langs kusten leven. Milieuvervuiling wordt gezien als een reden voor de recente vermindering in aantallen bruinvissen in Europa en delen van Noord-Amerika &lt;a href="https://publicwiki.deltares.nl/display/HBTHOME/Bruinvis+-+Phocaena+phocaena#Bruinvis-Phocaenaphocaena-2"&gt;#2&lt;/a&gt;.&lt;br&gt;De huidige dosis-effect relatie is van toepassing op de Noordzee.&lt;/p&gt;&lt;h1 id="Bruinvis-Phocaenaphocaena-Voorbeeldproject"&gt;Voorbeeld project&lt;/h1&gt;&lt;p&gt;Er is geen voorbeeldprojekt beschikbaar.&lt;/p&gt;</text>
					</Description>
				</SystemDescription>
				<SystemFlowDiagrams>
					<FlowDiagram name="adult">
						<From name="habitatgeschiktheid">
							<label>"habitatgeschiktheid"</label>
							<equation>min</equation>
							<To>waterdiepte</To>
						</From>
					</FlowDiagram>
				</SystemFlowDiagrams>
				<KnowledgeRules>
					<ResponseCurve name="waterdiepte">
						<inputLayers>
							<layer name="waterdiepte">
								<parameter_cat>TOBEFILLED</parameter_cat>
								<layer_filename>waterdiepte</layer_filename>
								<unit>"m"</unit>
								<statistic>minimum</statistic>
								<description>TOBEFILLED</description>
							</layer>
						</inputLayers>
						<Content>
							<type>ranges</type>
							<description>"Waterdiepte"</description>
							<author>"Marjolijn Haasnoot"</author>
							<date>2009-01-01</date>
							<references>
								<reference author="" year="2009" title="http://www.minlnv.nl/natura2000" journal="" identification=""/>
							</references>
							<valuesRanges>
								<parameter rangemin_input="0" rangemax_input="200" output="1"/>
								<parameter rangemin_input="200" rangemax_input="999" output="0"/>
							</valuesRanges>
						</Content>
						<outputLayers>
							<layer name="HSI_waterdiepte">
								<parameter_cat>HSI</parameter_cat>
								<layer_filename>HSI_waterdiepte</layer_filename>
								<unit>factor</unit>
								<statistic>average</statistic>
								<description>TOBEFILLED</description>
							</layer>
						</outputLayers>
					</ResponseCurve>
				</KnowledgeRules>
			</System>
		</ModelType>
	</Autecology>
	<TopicDescription>
		<Description language="NL">
			<text>&lt;h3 id="Bruinvis-Phocaenaphocaena-Algemeenvoorkomen"&gt;Algemeen voorkomen&lt;/h3&gt;&lt;p&gt;De Bruinvis (Phocoena phocoena; familie Phocaenidae) is de kleinste walvissoort in de Europese kustwateren. Bruinvissen zijn robuust van bouw en hebben in tegenstelling tot de meeste andere dolfijnen een afgeronde kop met een stompe snuit. Volwassen dieren zijn gemiddeld zo'n 1,5 m lang. De rugvin is klein en driehoekig van vorm. De rug is bruinachtig donkergrijs tot zwart (vandaar de naam), de onderzijde is wit en de flanken zijn grijs. Tussen de mondhoeken en de flippers bevindt zich een dunne zwarte streep. De soort weegt gemiddeld 50 tot 55 kg en maximaal 90 kg; mannetjes zijn iets forser dan vrouwtjes. De Bruinvis kan verward worden met de Tuimelaar (&lt;em&gt;Tursiops truncatus&lt;/em&gt;) doordat bij beide soorten kleurpatronen ontbreken. De Tuimelaar onderscheidt zich echter door zijn grotere formaat, zijn sikkelvormig gebogen rugvin en zijn lange snuit. Hij is bovendien veel zeldzamer dan bruinvissen in ons kustgebied, net als andere walvisachtigen. De Bruinvis wordt in relatief ondiep (tot 200 m) water waargenomen langs kusten en in baaien en gaat ook af en toe rivieren op. De soort leeft solitair of in kleine groepen, maar soms worden scholen van 50 tot 100 individuen gezien. De dieren communiceren onderling door middel van geluiden. Net als andere dolfijnen maken ze gebruik van echolocatie om te navigeren en te foerageren. Bruinvissen gebruiken hierbij zeer specifieke klikklanken &lt;a href="https://publicwiki.deltares.nl/display/HBTHOME/Bruinvis+-+Phocaena+phocaena#Bruinvis-Phocaenaphocaena-1"&gt;#1&lt;/a&gt;.&lt;/p&gt;&lt;h3 id="Bruinvis-Phocaenaphocaena-Voedselhabitatenstrategie"&gt;Voedselhabitat en strategie&lt;/h3&gt;&lt;p&gt;Het voedsel bestaat uit vissen, zoals Wijting (&lt;em&gt;Merlangius merlangus&lt;/em&gt;), Kabeljauw (&lt;em&gt;Gadus morhua&lt;/em&gt;), Puitaal (&lt;em&gt;Zoarces viviparus&lt;/em&gt;) en Haring (&lt;em&gt;Clupea harengus&lt;/em&gt;) en bijvoorbeeld inktvissen &lt;a href="https://publicwiki.deltares.nl/display/HBTHOME/Bruinvis+-+Phocaena+phocaena#Bruinvis-Phocaenaphocaena-1"&gt;#1&lt;/a&gt;.&lt;/p&gt;&lt;h3 id="Bruinvis-Phocaenaphocaena-Reproductieenmigratie"&gt;Reproductie en migratie&lt;/h3&gt;&lt;p&gt;De paartijd is in de zomer (juli), waarna tussen mei en juli van het volgende jaar één jong wordt geboren &lt;a href="https://publicwiki.deltares.nl/display/HBTHOME/Bruinvis+-+Phocaena+phocaena#Bruinvis-Phocaenaphocaena-1"&gt;#1&lt;/a&gt;.&lt;/p&gt;&lt;h3 id="Bruinvis-Phocaenaphocaena-Leeftijdenmortaliteit"&gt;Leeftijd en mortaliteit&lt;/h3&gt;&lt;p&gt;De Bruinvis kan 24 jaar oud worden maar het merendeel van de bruinvissen wordt waarschijnlijk niet ouder dan 12 jaar &lt;a href="https://publicwiki.deltares.nl/display/HBTHOME/Bruinvis+-+Phocaena+phocaena#Bruinvis-Phocaenaphocaena-1"&gt;#1&lt;/a&gt;.&lt;/p&gt;</text>
		</Description>
	</TopicDescription>
	<Documentation>
		<reference author="" year="2009" title="http://www.minlnv.nl/natura2000" journal="" identification="">
			<html>https://www.synbiosys.alterra.nl/natura2000/gebiedendatabase.aspx?zoek_gebiedsnaam_n2k=bruinvis</html>
		</reference>
		<reference author="" year="2009" title="http://www.soortenbank.nl" journal="" identification="">
			<html>http://www.soortenbank.nl/soorten.php?soortengroep=duikgids&amp;id=274&amp;menuentry=soorten</html>
		</reference>
	</Documentation>
	<DataSources/>
</AutecologyXML>
